// Master TyreSaathi Catalog & Mega Menu Database

export const MEGA_MENU_BRANDS = [
  { name: "Apollo", popular: true, count: "120+ Products" },
  { name: "Bridgestone", popular: true, count: "95+ Products" },
  { name: "Ceat", popular: true, count: "140+ Products" },
  { name: "Continental", popular: true, count: "60+ Products" },
  { name: "Clearance", tag: "Sale", count: "Special Deals" },
  { name: "Firestone", count: "35+ Products" },
  { name: "Goodyear", popular: true, count: "80+ Products" },
  { name: "JK Tyre", popular: true, count: "110+ Products" },
  { name: "Kelly", count: "25+ Products" },
  { name: "Michelin", popular: true, count: "75+ Products" },
  { name: "Pirelli", popular: true, count: "45+ Products" },
  { name: "Vredestein", count: "30+ Products" },
  { name: "Ralco", popular: true, count: "55+ Products" },
  { name: "reise", count: "20+ Products" },
  { name: "TVS Eurogrip", popular: true, count: "90+ Products" },
  { name: "Vee Rubber", count: "15+ Products" },
  { name: "Metzeler", count: "25+ Products" },
  { name: "Metro", count: "40+ Products" },
  { name: "ARF", count: "18+ Products" },
  { name: "ARL", count: "12+ Products" },
  { name: "Auto Boss", count: "30+ Products" },
  { name: "Classic", count: "22+ Products" },
  { name: "Galaxy", count: "15+ Products" },
  { name: "Maruti", count: "28+ Products" },
  { name: "META GOLD", count: "16+ Products" },
  { name: "Moly Lube", count: "14+ Products" },
  { name: "NEO Wheels", tag: "Alloy", count: "40+ Designs" },
  { name: "Onyx", count: "20+ Products" },
  { name: "PLATI Alloy Wheels", tag: "Alloy", count: "50+ Designs" },
  { name: "MY TVS", count: "35+ Products" },
  { name: "MRF", popular: true, count: "180+ Products" },
  { name: "Yokohama", popular: true, count: "65+ Products" },
];

export const TYRE_CATEGORIES = [
  { id: "two_wheeler", name: "Two-Wheeler (Bike / Scooter / EV)", icon: "🏍️" },
  { id: "passenger_car", name: "Passenger Car & Hatchback", icon: "🚗" },
  { id: "suv_muv", name: "SUV & Compact MUV", icon: "🚙" },
  { id: "commercial", name: "Commercial (Truck / Bus / LCV)", icon: "🚚" },
  { id: "tractor_agri", name: "Tractor & Agriculture Farm", icon: "🚜" },
  { id: "auto_rickshaw", name: "Auto Rickshaw (3-Wheeler)", icon: "🛺" },
  { id: "otr_industrial", name: "OTR & Industrial Crane", icon: "🏗️" },
  { id: "alloy_wheels", name: "Alloy Wheels & Designer Rims", icon: "✨" },
];

export const VEHICLE_TYPES = {
  two_wheeler: ["Scooter (Activa, Jupiter, Access)", "Motorcycle (100cc-150cc)", "Sports Bike (150cc-400cc)", "Electric Scooter (Ola, Ather, Chetak)", "Bullet / Royal Enfield Classic"],
  passenger_car: ["Hatchback (Swift, WagonR, i10, Tiago)", "Sedan (City, Verna, Dzire, Amaze)", "Premium Sedan (Octavia, Camry)"],
  suv_muv: ["Compact SUV (Brezza, Nexon, Creta, Seltos)", "Full-Size SUV (Scorpio, Thar, Safari, Fortuner)", "MUV / MPV (Innova, Ertiga, Carens)"],
  commercial: ["Small LCV (Tata Ace, Bolero Maxi Truck)", "Medium LCV (Eicher, 407)", "Heavy Commercial (10-Wheeler, 12-Wheeler Truck)", "Intercity Bus / Volvo"],
  tractor_agri: ["Tractor Front Steering", "Tractor Rear Traction (12.4/13.6/14.9)", "Harvester & Trailer"],
  auto_rickshaw: ["Passenger 3-Wheeler (Bajaj, Piaggio)", "Cargo Load Carrier 3-Wheeler", "Electric Auto (E-Rickshaw)"],
  otr_industrial: ["JCB Backhoe Loader", "Forklift & Warehouse Crane", "Mining Tipper Dumper"],
  alloy_wheels: ["13 Inch Alloys", "14 Inch Alloys", "15 Inch Alloys", "16 Inch Alloys", "17+ Inch Diamond Cut Alloys"]
};

export const POPULAR_SIZES = {
  two_wheeler: ["90/90-12", "100/90-17", "80/100-18", "2.75-17", "3.00-18", "140/70-17", "110/80-17", "120/80-18", "90/100-10"],
  passenger_car: ["145/80 R12", "155/80 R13", "165/80 R14", "175/65 R14", "185/65 R15", "185/70 R14", "195/65 R15", "205/55 R16", "205/60 R16"],
  suv_muv: ["215/60 R16", "215/65 R16", "235/65 R17", "265/65 R17", "215/60 R17", "225/65 R17", "255/60 R18", "265/60 R18"],
  commercial: ["10.00-20", "295/80 R22.5", "7.50-16", "8.25-16", "11.00-20", "155 R13 LT", "7.00 R15 LT"],
  tractor_agri: ["6.00-16", "12.4-28", "13.6-28", "14.9-28", "7.50-16", "16.9-28"],
  auto_rickshaw: ["4.00-8", "4.50-10", "145/70 R12", "3.75-12"],
  otr_industrial: ["12.5/80-18", "14.00-24", "16.9-28", "23.5-25"],
  alloy_wheels: ["PCD 100 4-Hole (14 Inch)", "PCD 100 4-Hole (15 Inch)", "PCD 114.3 5-Hole (16 Inch)", "PCD 114.3 5-Hole (17 Inch)"]
};

export const POPULAR_PATTERNS = [
  "MRF Zapper FX (Tubeless)",
  "MRF Nylogrip Ezeeride",
  "MRF ZVTV Premium",
  "MRF Wanderer Street AT",
  "MRF Super Lug 50",
  "Apollo Amazer 4G Life",
  "Apollo Alnac 4G",
  "Apollo Apterra AT2",
  "Apollo ActiGrip R1",
  "CEAT Secura Zoom",
  "CEAT Milaze X3",
  "CEAT CrossDrive AT",
  "CEAT Gripp X3",
  "Bridgestone Turanza T005",
  "Bridgestone Ecopia EP150",
  "Bridgestone B290",
  "Bridgestone Dueler D684",
  "Michelin Primacy 4 ST",
  "Michelin Energy XM2+",
  "Michelin LTX Trail",
  "Goodyear Assurance TripleMax 2",
  "Goodyear Wrangler AT SilentTrac",
  "JK Tyre UX Royale",
  "JK Tyre Elanzo Touring",
  "TVS Eurogrip Dragon Tube/Tubeless",
  "Ralco Speed Blaster",
  "Yokohama Earth-1 E400",
  "Yokohama Geolandar A/T G015"
];

export const SERVICE_TYPES = [
  { id: "cut_repair", name: "Tyre Cut & Sidewall Repair (टायर कट रिपेयर)", duration: "45 Mins", price: 350 },
  { id: "puncture", name: "Tubeless Puncture Repair (पंचर रिपेयर)", duration: "15 Mins", price: 100 },
  { id: "alignment", name: "3D Wheel Alignment & Balancing (अलाइनमेंट)", duration: "30 Mins", price: 450 },
  { id: "fitting", name: "New Tyre Fitting & Nitrogen Fill (फिटिंग)", duration: "20 Mins", price: 150 },
  { id: "doorstep", name: "Doorstep Emergency Assistance (घर/रास्ते पर सर्विस)", duration: "45 Mins", price: 499 },
  { id: "rotation", name: "Tyre Rotation & Brake Check (रोटेशन)", duration: "25 Mins", price: 250 },
];

export const SAMPLE_SHOPS = [
  {
    id: "shop-amr",
    name: "Cherry Tyre Park - AMR",
    ownerName: "Amrit Raj",
    phone: "080-2667-8473",
    rating: 4.8,
    reviewsCount: 128,
    address: "138/22/1, Sundar Complex, A.M. Ln, opp. to Chitresh Automobiles, Kalasipalyam New Extn, Nagarathpete, Bengaluru, Karnataka 560002",
    city: "Bengaluru",
    distanceKm: 1.2,
    isNearest: true,
    openingHours: "8:30 AM - 9:00 PM",
    coordinates: { lat: 12.9648, lng: 77.5815 },
    servicesOffered: ["Tyre Replacement", "Cut Repair", "Wheel Alignment", "Nitrogen Air"],
    isOpen: true
  },
  {
    id: "shop-raj",
    name: "Raja Tyre Center & Service",
    ownerName: "Rajesh Kumar",
    phone: "98765-43210",
    rating: 4.7,
    reviewsCount: 94,
    address: "Shop 4, Main Market Road, Near City Petrol Pump, Koramangala 5th Block, Bengaluru, Karnataka 560095",
    city: "Bengaluru",
    distanceKm: 2.8,
    isNearest: true,
    openingHours: "9:00 AM - 9:30 PM",
    coordinates: { lat: 12.9352, lng: 77.6245 },
    servicesOffered: ["Tyre Sales", "Puncture Repair", "Doorstep Van"],
    isOpen: true
  },
  {
    id: "shop-atg",
    name: "Cherry Tyre Park - ATG",
    ownerName: "Thirumoorthy",
    phone: "080-3589-3314",
    rating: 4.6,
    reviewsCount: 76,
    address: "# 4/830, Vinayaga Complex, Erode Main Road, Gobichetty Palayam, Tamil Nadu 638476",
    city: "Erode",
    distanceKm: 8.5,
    isNearest: false,
    openingHours: "9:00 AM - 8:30 PM",
    coordinates: { lat: 11.4552, lng: 77.4326 },
    servicesOffered: ["All Heavy & Bike Tyres", "Wheel Balancing", "Tube Vulcanizing"],
    isOpen: true
  },
  {
    id: "shop-delhi",
    name: "TyreSaathi Super Hub - NCR",
    ownerName: "Vikram Malhotra",
    phone: "011-4567-8900",
    rating: 4.9,
    reviewsCount: 210,
    address: "Plot 12, Auto Market, Sector 14, Ring Road, New Delhi, Delhi 110028",
    city: "Delhi NCR",
    distanceKm: 14.2,
    isNearest: false,
    openingHours: "8:00 AM - 10:00 PM",
    coordinates: { lat: 28.6139, lng: 77.2090 },
    servicesOffered: ["Complete Wheel Care", "Alloy Wheels", "Doorstep Mobile Van"],
    isOpen: true
  },
  {
    id: "shop-mumbai",
    name: "Metro Wheels & Tyre Hub",
    ownerName: "Sachin Patil",
    phone: "022-2876-5432",
    rating: 4.7,
    reviewsCount: 145,
    address: "Shop 18, Link Road, Near Metro Station, Andheri West, Mumbai, Maharashtra 400053",
    city: "Mumbai",
    distanceKm: 18.0,
    isNearest: false,
    openingHours: "9:00 AM - 9:00 PM",
    coordinates: { lat: 19.1363, lng: 72.8277 },
    servicesOffered: ["Tubeless Specialist", "Nitrogen Air", "Alloys"],
    isOpen: true
  }
];

export const INITIAL_FEATURED_PRODUCTS = [
  {
    id: "prod-1",
    productName: "MRF Zapper FX 100/90-17 Tubeless Bike Tyre",
    productType: "tyre",
    brandName: "MRF",
    categoryName: "Two-Wheeler (Bike / Scooter / EV)",
    vehicleTypeName: "Motorcycle (100cc-150cc)",
    sizeName: "100/90-17",
    modelName: "MRF Zapper FX (Tubeless)",
    originalPrice: 2450,
    offerPrice: 2099,
    stock: 8,
    published: true,
    condition: "new",
    shopId: "shop-amr",
    shopName: "Cherry Tyre Park - AMR",
    shopPhone: "080-2667-8473",
    distanceKm: 1.2,
    isNearest: true,
    images: [
      "https://images.unsplash.com/photo-1578844251758-2f71da64c96f?w=600&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=600&auto=format&fit=crop&q=80"
    ],
    description: "High performance bike rear tyre with deep water grooving and 5 years manufacturer warranty."
  },
  {
    id: "prod-2",
    productName: "Apollo Amazer 4G Life 185/65 R15 Car Tyre",
    productType: "tyre",
    brandName: "Apollo",
    categoryName: "Passenger Car & Hatchback",
    vehicleTypeName: "Sedan (City, Verna, Dzire, Amaze)",
    sizeName: "185/65 R15",
    modelName: "Apollo Amazer 4G Life",
    originalPrice: 5200,
    offerPrice: 4350,
    stock: 12,
    published: true,
    condition: "new",
    shopId: "shop-amr",
    shopName: "Cherry Tyre Park - AMR",
    shopPhone: "080-2667-8473",
    distanceKm: 1.2,
    isNearest: true,
    images: [
      "https://images.unsplash.com/photo-1549497538-303791108f95?w=600&auto=format&fit=crop&q=80"
    ],
    description: "Guaranteed 100,000 km tread life with ultra micro-silica compound for maximum fuel efficiency."
  },
  {
    id: "prod-3",
    productName: "CEAT Milaze X3 165/80 R14 Durable Car Tyre",
    productType: "tyre",
    brandName: "Ceat",
    categoryName: "Passenger Car & Hatchback",
    vehicleTypeName: "Hatchback (Swift, WagonR, i10, Tiago)",
    sizeName: "165/80 R14",
    modelName: "CEAT Milaze X3",
    originalPrice: 4100,
    offerPrice: 3499,
    stock: 6,
    published: true,
    condition: "new",
    shopId: "shop-raj",
    shopName: "Raja Tyre Center & Service",
    shopPhone: "98765-43210",
    distanceKm: 2.8,
    isNearest: true,
    images: [
      "https://images.unsplash.com/photo-1563720223185-11003d516935?w=600&auto=format&fit=crop&q=80"
    ],
    description: "Specially crafted for Indian roads with high rubber content and 3 years unconditional warranty."
  },
  {
    id: "prod-4",
    productName: "Bridgestone Turanza T005 205/55 R16 Premium Tyre",
    productType: "tyre",
    brandName: "Bridgestone",
    categoryName: "Passenger Car & Hatchback",
    vehicleTypeName: "Premium Sedan (Octavia, Camry)",
    sizeName: "205/55 R16",
    modelName: "Bridgestone Turanza T005",
    originalPrice: 8900,
    offerPrice: 7650,
    stock: 4,
    published: true,
    condition: "new",
    shopId: "shop-atg",
    shopName: "Cherry Tyre Park - ATG",
    shopPhone: "080-3589-3314",
    distanceKm: 8.5,
    isNearest: false,
    images: [
      "https://images.unsplash.com/photo-1607860108855-64acf2078ed9?w=600&auto=format&fit=crop&q=80"
    ],
    description: "Ultra quiet luxury touring tyre with highest safety rating on wet surfaces."
  },
  {
    id: "prod-5",
    productName: "PLATI 16 Inch Diamond Cut Alloy Wheels (Set of 4)",
    productType: "custom",
    brandName: "PLATI Alloy Wheels",
    categoryName: "Alloy Wheels & Designer Rims",
    vehicleTypeName: "16 Inch Alloys",
    sizeName: "PCD 114.3 5-Hole (16 Inch)",
    modelName: "PLATI Diamond Cut Racing Black",
    originalPrice: 36000,
    offerPrice: 29999,
    stock: 2,
    published: true,
    condition: "new",
    shopId: "shop-delhi",
    shopName: "TyreSaathi Super Hub - NCR",
    shopPhone: "011-4567-8900",
    distanceKm: 14.2,
    isNearest: false,
    images: [
      "https://images.unsplash.com/photo-1584345604476-8ec5e12e42dd?w=600&auto=format&fit=crop&q=80"
    ],
    description: "Lightweight aircraft grade alloy wheels with hyper-gloss CNC diamond cut finish."
  }
];
